import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  mainSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/overview" },
      collapsible: true,
      collapsed: false,
      items: [
        "architecture/system-design",
        "architecture/data-flow",
        "architecture/technology-stack",
        "architecture/security-model",
      ],
    },
    {
      type: "category",
      label: "Development",
      link: { type: "doc", id: "development/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "development/getting-started",
        "development/environment-setup",
        "development/project-structure",
        "development/workflows",
        "development/testing",
        "development/deployment",
      ],
    },
    {
      type: "category",
      label: "Standards",
      link: { type: "doc", id: "standards/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "standards/style-guide",
        "standards/naming-conventions",
        "standards/code-quality",
        "standards/documentation-standards",
        "standards/content-standards",
        "standards/metadata-guide",
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: { type: "doc", id: "guides/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "guides/mermaid-guide",
        "guides/ai-integration",
        "guides/contributing",
        "guides/knowledge-graph-guide",
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "doc", id: "reference/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "reference/glossary",
        "reference/roadmap",
        "reference/changelog",
        "reference/quality-standards",
        "reference/api-reference",
      ],
    },
  ],

  curriculumSidebar: [
    {
      type: "autogenerated",
      dirName: "curriculum",
    },
  ],

  lessonsSidebar: [
    {
      type: "autogenerated",
      dirName: "lessons",
    },
  ],

  projectsSidebar: [
    {
      type: "autogenerated",
      dirName: "projects",
    },
  ],

  labsSidebar: [
    {
      type: "autogenerated",
      dirName: "labs",
    },
  ],

  careerSidebar: [
    {
      type: "autogenerated",
      dirName: "career",
    },
  ],

  certificationsSidebar: [
    {
      type: "autogenerated",
      dirName: "certifications",
    },
  ],
};

export default sidebars;
