import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Custom sidebarItemsGenerator for lessons:
 * - Categories link to the first actual lesson (not index.md)
 * - index.md items are hidden from the sidebar
 * - Modules appear as collapsible categories
 */
async function lessonsSidebarGenerator({ defaultSidebarItemsGenerator, ...args }: any) {
  const items = await defaultSidebarItemsGenerator(args);
  return items.map((item: any) => {
    if (item.type === "category") {
      // Find first non-index doc in the category
      const firstDoc = item.items.find((i: any) => i.type === "doc" && !i.id.endsWith("/index"));
      return {
        ...item,
        // Link category to first actual lesson, not index.md
        link: firstDoc ? { type: "doc", id: firstDoc.id } : undefined,
        // Hide index.md items from sidebar
        items: item.items.filter((i: any) => i.type !== "doc" || !i.id.endsWith("/index")),
      };
    }
    return item;
  });
}

const sidebars: SidebarsConfig = {
  // This is the DEFAULT sidebar — shows the Cloud Engineering lessons tree
  // Custom generator: categories link to first lesson, index.md items hidden
  lessonsSidebar: [
    {
      type: "autogenerated",
      dirName: "lessons",
      // @ts-expect-error - Docusaurus v3 supports sidebarItemsGenerator at runtime
      sidebarItemsGenerator: lessonsSidebarGenerator,
    },
  ],

  // Developer documentation sidebar (used via displayed_sidebar: devSidebar)
  devSidebar: [
    {
      type: "doc",
      id: "intro",
      label: "Introduction",
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "doc", id: "architecture/overview" },
      collapsible: true,
      collapsed: false,
      items: [
        "architecture/system-design",
        "architecture/data-flow",
        "architecture/technology-stack",
        "architecture/security-model",
      ],
    },
    {
      type: "category",
      label: "Development",
      link: { type: "doc", id: "development/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "development/getting-started",
        "development/environment-setup",
        "development/project-structure",
        "development/workflows",
        "development/testing",
        "development/deployment",
      ],
    },
    {
      type: "category",
      label: "Standards",
      link: { type: "doc", id: "standards/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "standards/style-guide",
        "standards/naming-conventions",
        "standards/code-quality",
        "standards/documentation-standards",
        "standards/content-standards",
        "standards/metadata-guide",
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: { type: "doc", id: "guides/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "guides/mermaid-guide",
        "guides/ai-integration",
        "guides/contributing",
        "guides/knowledge-graph-guide",
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "doc", id: "reference/overview" },
      collapsible: true,
      collapsed: true,
      items: [
        "reference/glossary",
        "reference/roadmap",
        "reference/changelog",
        "reference/quality-standards",
        "reference/api-reference",
      ],
    },
  ],

  // Legacy sidebars kept for compatibility
  curriculumSidebar: [
    {
      type: "autogenerated",
      dirName: "curriculum",
    },
  ],

  projectsSidebar: [
    {
      type: "autogenerated",
      dirName: "projects",
    },
  ],

  labsSidebar: [
    {
      type: "autogenerated",
      dirName: "labs",
    },
  ],

  careerSidebar: [
    {
      type: "autogenerated",
      dirName: "career",
    },
  ],

  certificationsSidebar: [
    {
      type: "autogenerated",
      dirName: "certifications",
    },
  ],
};

export default sidebars;
